twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig'] # accepte plusieurs thèmes
    globals: 
        app_name: 'Store 2'
        locales: '%app.locales%'
        search_form: '@App\Twig\SearchExtension'
when@test:
    twig:
        strict_variables: true
