twig:
    cache: false
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig'] # accepte plusieurs thèmes
    globals: 
        app_name: 'Lesekoya'
        locales: '%app.locales%'
        search_form: '@App\Twig\SearchExtension'
        navs: '@App\Twig\NavExtension'
        categories: '@App\Twig\CategoryExtention'
        parentCategorys: '@App\Twig\CategoryParentExtention'
        gg_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
        base: prod
        site:
            version: '1.0' 
            name: 'lesekoya'
            desc: 'Praesent dapibus, neque id cursus ucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus.'
            email: 'contact@store.sn'
            path_logo: 'lesekoya2.png'
            path_logo_icon: 'lesekoya-icon.png'
            current_name: '$'
            current: 'USD'
            tel_1: '221781278288'
            link: "https://lest.sn"
            mission_text: 'text à definir'
            user_empty: 'empty.png'
            orange_money: '+221 77 801 06 46'
            code_postal: 'DK 11300'
            adresse: 'Sacre coeur 2'
            ville: 'Dakar'
            pays: 'Sénégal'
            whatsapp: "https://api.whatsapp.com/send?phone=221778010646&text=Salut, je vous contacte depuis votre site lest.sn"
            facebook: 'https://www.facebook.com/Les-Spécialistes-de-la-Technologie-LEST-575426226469195/'

when@test:
    twig:
        strict_variables: true
