twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig'] # accepte plusieurs thèmes
    globals: 
        app_name: 'LeSekoya'
        locales: '%app.locales%'
        search_form: '@App\Twig\SearchExtension'
        navs: '@App\Twig\NavExtension'
        site: 
            name: 'leSekoya'
            email: 'leseoya@gmail.com'
            current_name: 'F cfa'
            current: 'XOF'
when@test:
    twig:
        strict_variables: true
